# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_hasse_impl <- function(scores, serial_pref) {
    .Call('_rPref_get_hasse_impl', PACKAGE = 'rPref', scores, serial_pref)
}

pref_select_top_impl <- function(scores, serial_pref, N, alpha, top, at_least, toplevel, and_connected, show_levels) {
    .Call('_rPref_pref_select_top_impl', PACKAGE = 'rPref', scores, serial_pref, N, alpha, top, at_least, toplevel, and_connected, show_levels)
}

grouped_pref_sel_top_impl <- function(indices, scores, serial_pref, N, alpha, top, at_least, toplevel, and_connected, show_levels) {
    .Call('_rPref_grouped_pref_sel_top_impl', PACKAGE = 'rPref', indices, scores, serial_pref, N, alpha, top, at_least, toplevel, and_connected, show_levels)
}

pref_select_impl <- function(scores, serial_pref, N, alpha) {
    .Call('_rPref_pref_select_impl', PACKAGE = 'rPref', scores, serial_pref, N, alpha)
}

grouped_pref_sel_impl <- function(indices, scores, serial_pref, N, alpha) {
    .Call('_rPref_grouped_pref_sel_impl', PACKAGE = 'rPref', indices, scores, serial_pref, N, alpha)
}

